version: '3.8'

services:
  app:
    image: merch-store:latest
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=avito
      - DB_PASSWORD=avito
      - DB_NAME=avito_shop
      - JWT_SECRET=supersecretkey
      - SERVER_PORT=8080
    networks:
      - merch-net
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "sleep 1 && ./merch-store"]

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=avito
      - POSTGRES_PASSWORD=avito
      - POSTGRES_DB=avito_shop
    networks:
      - merch-net
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./migrations/001_init.up.sql:/docker-entrypoint-initdb.d/001_init.up.sql
      - ./migrations/002_seed_items.up.sql:/docker-entrypoint-initdb.d/002_seed_items.up.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U avito -d avito_shop"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  merch-net:
    driver: bridge

volumes:
  db-data: